[build]
  base = "."
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://military-asset-management-system-x5x4.onrender.com"
  REACT_APP_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
